name: Katanokoya Checker

on:
  schedule:
    - cron: '0 * * * *'   # 毎時0分に実行（UTC基準、日本時間は+9時間）
  workflow_dispatch:       # 手動実行も可能

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests icalendar
      - name: Run script
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python check.py
